name: Test
on:
  push:
    branches-ignore: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches-ignore: [ master ]
jobs:
  Deploy-GitHub-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - run: yarn build
